apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "depi4ops.labels" . | nindent 4 }}
    app: mongo
spec:
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          args:
            - "--storageEngine={{ .Values.mongo.storageEngine }}"
          ports:
            - containerPort: {{ .Values.mongo.service.targetPort }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          {{- with .Values.mongo.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: mongo-storage
          {{- if .Values.mongo.persistence.enabled }}
          persistentVolumeClaim:
            claimName: mongo-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
