apiVersion: v1
kind: Secret
metadata:
  name: payload-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "depi4ops.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  PAYLOAD_SECRET: {{ .Values.secret.payloadSecret | quote }}
